# Generated by Django 3.0.5 on 2021-04-23 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streamapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='stamp',
            field=models.TimeField(),
        ),
    ]
